apiVersion: gemfire.tanzu.vmware.com/v1
kind: GemFireCluster
metadata:
  name: gemfire1
  namespace: test-gf
spec:
  image: registry.pivotal.io/tanzu-gemfire-for-kubernetes/gemfire-k8s:1.0.0
  locators:
    persistentVolumeClaim:
      resources:
        requests:
          storage: 2Gi
    replicas: 2
    resources:
      requests:
        memory: 1Gi
  metrics:
    emission: Default
  resourceManager:
    criticalHeapPercentage: 90
    evictionHeapPercentage: 75
  serialization:
    pdx:
      readSerialized: true
  servers:
    persistentVolumeClaim:
      resources:
        requests:
          storage: 4Gi
    replicas: 4
    resources:
      requests:
        memory: 1Gi
